on:
  pull_request:
    branches:
      - main
name: Validation Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create back-end .env.test
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB_TEST}}
          envkey_DATABASE_URL: ${{secrets.POSTGRES_DATABASE_URL_TEST}}
          directory: back-end/
          file_name: .env.test
          fail_on_empty: true

      - name: Run Tests
        run: docker-compose -f docker-compose-tests.yml run node_app npm run test:merge
